services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-alpha1
    volumes:
      - data01:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.0.0-alpha1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  elastictest:
    container_name: elastictest
    build:
      context: .
      dockerfile: Dockerfile
    image: elastictest:latest
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - 8080:8080
    restart: always
    networks:
      - es-net
networks:
  es-net:
    driver: bridge

volumes:
  data01:
    driver: local
